#ifndef DIFF_HUNKS_H
#define DIFF_HUNKS_H

#include "hash.h"

struct repository;

/*
 * Precomputed diff hunks stored in .git/objects/diff-hunks/.
 *
 * Generated by `git diff-hunks write --reachable` or `--path <file>`.
 * Consumed by blame, diffstat, and other tools via the cache API below.
 * Deletion-safe: consumers degrade gracefully when files are absent.
 */

/* Each hunk is 12 bytes: old_start(4) + old_count(2) + new_start(4) + new_count(2) */
#define DIFF_HUNKS_ENTRY_SIZE 12

struct precomputed_hunk {
	uint32_t old_start;
	uint16_t old_count;
	uint32_t new_start;
	uint16_t new_count;
};

/*
 * Result of diff_hunks_get(). The hunk_data pointer is into mmap'd
 * file data and is valid until the owning diff_hunks_cache is freed.
 */
struct precomputed_entry {
	uint32_t num_hunks;
	const unsigned char *hunk_data;
};

/*
 * Opaque cache for precomputed diff hunks. Loads per-path files
 * lazily on first access and caches them for the lifetime of the
 * cache object.
 */
struct diff_hunks_cache;

struct diff_hunks_cache *diff_hunks_cache_init(struct repository *r,
					       int xdl_opts);
void diff_hunks_cache_free(struct diff_hunks_cache *c);

/*
 * Look up precomputed hunks for (commit, parent, path).
 * Returns 1 if found, 0 on miss (caller should fall back to xdiff).
 */
int diff_hunks_get(struct diff_hunks_cache *c,
		   const struct object_id *commit_oid,
		   const struct object_id *parent_oid,
		   const char *path,
		   struct precomputed_entry *out);


/*
 * Decode a single hunk from the raw on-disk format.
 */
static inline void decode_precomputed_hunk(const unsigned char *data,
					   struct precomputed_hunk *h)
{
	h->old_start = get_be32(data);
	h->old_count = get_be16(data + 4);
	h->new_start = get_be32(data + 6);
	h->new_count = get_be16(data + 10);
}

#endif /* DIFF_HUNKS_H */
