#!/bin/bash
#
# gen-symmap.sh - Generate a symbol map for batch memory instrumentation
#
# Produces a TSV mapping every .data/.bss byte range to its owning object
# file and (where available) individual symbol name. Two data sources:
#
#   1. Linker map file (-Wl,-Map): per-.o address ranges
#   2. Per-object nm -S: individual symbol names + sizes
#
# The output has object-file granularity (which .o owns each byte range)
# plus symbol-level detail where nm provides it. This is enough to
# separate CRT objects from git objects and identify individual statics.
#
# Usage:
#   ./gen-symmap.sh <linker-map-file> [object-dir] > git.symmap
#
# The linker map is generated by:
#   make LDFLAGS="-Wl,-Map,git.map" git  (or git.exe on Windows)

set -e

MAP="$1"
OBJDIR="${2:-.}"

if [ ! -f "$MAP" ]; then
	echo "usage: $0 <linker-map-file> [object-dir]" >&2
	exit 1
fi

# --- Parse section boundaries from the map ---
data_start=$(awk '/^\.data\s/ { printf "%s", $2 }' "$MAP")
data_size=$( awk '/^\.data\s/ { printf "%s", $3 }' "$MAP")
bss_start=$( awk '/^\.bss\s/  { printf "%s", $2 }' "$MAP")
bss_size=$(  awk '/^\.bss\s/  { printf "%s", $3 }' "$MAP")

echo "# symmap v1"
echo "# data_start=$data_start data_size=$data_size"
echo "# bss_start=$bss_start bss_size=$bss_size"
echo "# section	offset	size	object	symbol	source"

# --- Parse per-object ranges from the map file ---
# Map file format for .data/.bss entries:
#  .data  0xADDRESS  0xSIZE  path/to/file.o
#                    0xADDRESS  symbol_name   (optional, indented)
awk -v data_start="$data_start" -v bss_start="$bss_start" '
BEGIN {
	section = ""
	sec_base["data"] = strtonum(data_start)
	sec_base["bss"]  = strtonum(bss_start)
}

# Track which section we are in
/^\.data\s/ { section = "data"; next }
/^\.bss\s/  { section = "bss";  next }
/^\./       { section = "";      next }

# Skip non-section lines
section == "" { next }

# Object file contribution: " .data  0xADDR  0xSIZE  path.o"
/^ \.(data|bss)\s+0x[0-9a-f]+\s+0x[0-9a-f]+\s+\S/ {
	addr  = strtonum($2)
	size  = strtonum($3)
	obj   = $4
	if (size > 0) {
		offset = addr - sec_base[section]
		printf "%s\t%d\t%d\t%s\t\t\n", section, offset, size, obj
	}
	next
}

# Named symbol within a section: "   0xADDR  symbol_name"
/^\s+0x[0-9a-f]+\s+[a-zA-Z_]/ && section != "" {
	addr = strtonum($1)
	sym  = $2
	offset = addr - sec_base[section]
	# Size unknown from map alone; emit 0
	printf "%s\t%d\t0\t\t%s\t\n", section, offset, sym
	next
}

# Padding: " *fill*  0xADDR  0xSIZE"
/\*fill\*/ && section != "" {
	addr = strtonum($2)
	size = strtonum($3)
	if (size > 0) {
		offset = addr - sec_base[section]
		printf "%s\t%d\t%d\t*fill*\t\t\n", section, offset, size
	}
}
' "$MAP"

# --- Augment with per-object nm for individual symbol detail ---
# This gives us names + sizes for statics that the map only shows as
# byte ranges. We output these as supplementary lines.
if [ -d "$OBJDIR" ]; then
	find "$OBJDIR" -name '*.o' -print0 2>/dev/null | \
	while IFS= read -r -d '' obj; do
		nm -S "$obj" 2>/dev/null | \
		grep -E ' [dDbB] ' | \
		grep -v '\.data\|\.bss' | \
		while read addr size type name rest; do
			# Relative offset within this object's section
			printf "# nm\t%s\t%s\t%s\t%s\t%s\n" \
				"$type" "$addr" "$size" "$name" "$obj"
		done
	done
fi
